In [1]:
import pandas as pd
import numpy as np
import os
import numpy as np


df = pd.read_csv("eif3a_full.csv")
print(df)

FileNotFoundError: [Errno 2] File eif3a_full.csv does not exist: 'eif3a_full.csv'

In [ ]:
train_All_1 = df.iloc[:,2]
test_all_1 = df.iloc[:,3]
# print(train_All_1)
# print(test_all_1)

In [2]:
pos_train_seq = train_All_1[0:711,]
neg_train_seq = train_All_1[711:,]
# print(len(pos_train_seq),"sadasdas")
# print(len(neg_train_seq),"*********")
# print(pos_train_seq)

NameError: name 'train_All_1' is not defined

In [4]:
pos_test_seq = test_all_1[0:45,]
neg_test_seq = test_all_1[45:90,]

X_test = np.array(test_all_1[0:90])
# X_test = np.mat(X_test)
print(X_test)
# print(X_test.shape)
# print(len(pos_test_seq),"sadasdas")
# print(len(neg_test_seq),"*********")
# print(neg_test_seq)

['TGCCCCTCCCTCCGGGTGGAACTTCCCCCTCACCGCCAGAC'
 'CCCCCGCCTCAGTTGTCTAAACTTCGGGCTCTCTTCCACCC'
 'AAGTGGTGAGCTGCGACGTGACTGGCTAGCTGCGTGGGTAC'
 'AGACAGTGAAAGTGAAATGGACTGATTTGCACTCTTGGTTC'
 'CTTCGGCGGAGCCTGGGCTGACCAGCCAGGACAGCGGGGTA'
 'CTTTCCTCACATTTCCAGGAACTGAGTATCTACCAAGATCA'
 'ACGACTTCTCCCTTCTTTGAACTGGACCCCGCGAGCACCAG'
 'TTTAAATTCCCGGCTCGGGGACCTCCACGCACCGCGGCTAG'
 'AGCGAGGAGGCTATTTCCAGACACTTCCACCCCTCTCTGGC'
 'CGCCGGCTTCTCCCGCAGTGACTTGAGAAGGGTCAGTGAAA'
 'CCATCTTCGCGGTAGCTGGGACCGCCGTTCAGGTAAGAATG'
 'GCTTGCTGCTGTCTCTGGGAACTGGGTGCCAGCGCTGAGGG'
 'TCACATCTCTTACCATAAAAACTGCATTGAAATTGAAAATG'
 'CATTTTGGAGAGCCTAATAAACTGTTATTACAGTTTCTCTA'
 'GGACTCATTTATTGAGCAAGACTTATATTTATCTCTTCATT'
 'GCCGAGGAGCTCAAGCCCGGACCAATCCCCACGTTCCGGGC'
 'GCCGCCGCGGAGCTTCCCGAACCTCTTCAGCCGCCCGGAGC'
 'TTTTCTCCACACAGGCAGGGACTGGCTGCCAACCCCTCCGG'
 'CACACACATTCCATTCCAAAACTGATTTTATAAAGACATTT'
 'CCCTTCCCCACCCTTCCAGAACACACACATTCCATTCCAAA'
 'TGGGCGGCGGGAATCCGCGGACATCGGGTCGGGTCTAGGCT'
 'TCCGGAACAGTCGACGGCAGACTCCGGCCCGCTGAGCCACC'
 'TTCTCCTG

In [5]:
y_train = np.array(["positive","negative"])
y_train = y_train.repeat(711)
y_train = np.mat(y_train).transpose()
# y_train = np.transpose(y_train)
# print(y_train)
print(y_train.shape)
print(type(y_train))
# print(type(y_train))
# print(len(y_train))

(1422, 1)
<class 'numpy.matrix'>


In [6]:
y_test = np.array(["positive","negative"])
y_test = y_test.repeat(45)
# print(y_test)


In [7]:
from collections import OrderedDict
CHAR_TO_INT = OrderedDict([('A', 0), ('T', 1), ('G', 2), ('C', 3), ('N', 4)])

In [8]:
def char_to_int(seq):
    return [CHAR_TO_INT[x] for x in seq.upper()]

In [22]:
char_to_int(X_test)
# print(X_test)

AttributeError: 'numpy.ndarray' object has no attribute 'upper'

In [23]:
def int_to_onehot(seqs, dim=4):
    """Special nucleotides will be encoded as [0, 0, 0, 0]."""
    seqs = np.atleast_2d(np.asarray(seqs))
    n = seqs.shape[0]
    l = seqs.shape[1]
    enc_seqs = np.zeros((n, l, dim), dtype='int8')
    for i in range(dim):
        t = seqs == i
        enc_seqs[t, i] = 1
    return enc_seqs

In [24]:
def seq_to_mat(seq):
    seq_len = len(seq)
    seq = seq.replace('A','0')
    seq = seq.replace('a','0')
    seq = seq.replace('C','1')
    seq = seq.replace('c','1')
    seq = seq.replace('G','2')
    seq = seq.replace('g','2')
    seq = seq.replace('T','3')
    seq = seq.replace('t','3')
    seq = seq.replace('U','3')
    seq = seq.replace('u','3')
    seq = seq.replace('N','4') #some cases have N in sequence
    seq = seq.replace('n','4')
    seq_code = np.zeros((4,seq_len), dtype='float16')
    for i in range(seq_len):
        if int(seq[i]) != 4:
            seq_code[int(seq[i]),i] = 1
        else:
            seq_code[0:4,i] = np.tile(0.25,4)
    return np.transpose(seq_code)

In [25]:
def seq_to_1hot(seq,randomsel=True):
	'converts the sequence to one-hot encoding'
	import random
	seq_len = len(seq)
	seq= seq.upper()
	seq_code = np.zeros((4,seq_len), dtype='int')
	for i in range(seq_len):
		nt = seq[i]
		if nt == 'A':
		    seq_code[0,i] = 1
		elif nt == 'C':
		    seq_code[1,i] = 1
		elif nt == 'G':
		    seq_code[2,i] = 1
		elif nt == 'T':
		    seq_code[3,i] = 1
		elif randomsel:
		    rn = random.randint(0,3)
		    seq_code[rn,i] = 1
	return seq_code



In [40]:
# seq_to_1hot(X_test)
print("X_test length",len(X_test))
num = 0
lst = []
for seq in X_test:
    x = seq_to_mat(seq).tolist()
    lst.extend(x)

Xl_test = np.array(lst)
print(X_test)

X_test length 90
['TGCCCCTCCCTCCGGGTGGAACTTCCCCCTCACCGCCAGAC'
 'CCCCCGCCTCAGTTGTCTAAACTTCGGGCTCTCTTCCACCC'
 'AAGTGGTGAGCTGCGACGTGACTGGCTAGCTGCGTGGGTAC'
 'AGACAGTGAAAGTGAAATGGACTGATTTGCACTCTTGGTTC'
 'CTTCGGCGGAGCCTGGGCTGACCAGCCAGGACAGCGGGGTA'
 'CTTTCCTCACATTTCCAGGAACTGAGTATCTACCAAGATCA'
 'ACGACTTCTCCCTTCTTTGAACTGGACCCCGCGAGCACCAG'
 'TTTAAATTCCCGGCTCGGGGACCTCCACGCACCGCGGCTAG'
 'AGCGAGGAGGCTATTTCCAGACACTTCCACCCCTCTCTGGC'
 'CGCCGGCTTCTCCCGCAGTGACTTGAGAAGGGTCAGTGAAA'
 'CCATCTTCGCGGTAGCTGGGACCGCCGTTCAGGTAAGAATG'
 'GCTTGCTGCTGTCTCTGGGAACTGGGTGCCAGCGCTGAGGG'
 'TCACATCTCTTACCATAAAAACTGCATTGAAATTGAAAATG'
 'CATTTTGGAGAGCCTAATAAACTGTTATTACAGTTTCTCTA'
 'GGACTCATTTATTGAGCAAGACTTATATTTATCTCTTCATT'
 'GCCGAGGAGCTCAAGCCCGGACCAATCCCCACGTTCCGGGC'
 'GCCGCCGCGGAGCTTCCCGAACCTCTTCAGCCGCCCGGAGC'
 'TTTTCTCCACACAGGCAGGGACTGGCTGCCAACCCCTCCGG'
 'CACACACATTCCATTCCAAAACTGATTTTATAAAGACATTT'
 'CCCTTCCCCACCCTTCCAGAACACACACATTCCATTCCAAA'
 'TGGGCGGCGGGAATCCGCGGACATCGGGTCGGGTCTAGGCT'
 'TCCGGAACAGTCGACGGCAGACTCCGGCCCGCTGAG

In [38]:
print("x_train one hot encoding")
lst = []
X_train = train_All_1
for seq in X_train:
    x = seq_to_mat(seq).tolist()
    lst.extend(x)
X_train = np.array(lst)
print(X_train)




x_train one hot encoding
[[0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 1. 0.]]


In [37]:
# print(seq_to_mat("AGCTCAGT"))
print(type(seq_to_1hot("AGCTCAGT")))

x = seq_to_mat("AGCTCAGT").tolist()
print(len(x))
y = seq_to_mat("ACTCTTAC").tolist()
x.extend(y)
print(len(x))

x = np.array(x)
print(x)

print(x.shape)

<class 'numpy.ndarray'>
8
16
[[1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]
(16, 4)


In [32]:
import numpy as np
import keras
# 固定随机数种子以复现结果
seed=13
np.random.seed(seed)

# 创建 1 维向量，并扩展维度适应 Keras 对输入的要求， data_1d 的大小为 (1, 25, 1)
data_1d = np.random.normal(size=25)
print(data_1d)
print(data_1d.shape)
data_1d = np.expand_dims(data_1d, 0)
print(data_1d)
print(data_1d.shape)
data_1d = np.expand_dims(data_1d, 2)
print(data_1d)
print(data_1d.shape)

[-0.71239066  0.75376638 -0.04450308  0.45181234  1.34510171  0.53233789
  1.3501879   0.86121137  1.47868574 -1.04537713 -0.78898902 -1.26160595
  0.56284679 -0.24332625  0.9137407   0.31735092  0.12730328  2.15038297
  0.60628866 -0.02677165 -0.98416078  1.19070527  0.95283061 -1.08718159
 -0.14521133]
(25,)
[[-0.71239066  0.75376638 -0.04450308  0.45181234  1.34510171  0.53233789
   1.3501879   0.86121137  1.47868574 -1.04537713 -0.78898902 -1.26160595
   0.56284679 -0.24332625  0.9137407   0.31735092  0.12730328  2.15038297
   0.60628866 -0.02677165 -0.98416078  1.19070527  0.95283061 -1.08718159
  -0.14521133]]
(1, 25)
[[[-0.71239066]
  [ 0.75376638]
  [-0.04450308]
  [ 0.45181234]
  [ 1.34510171]
  [ 0.53233789]
  [ 1.3501879 ]
  [ 0.86121137]
  [ 1.47868574]
  [-1.04537713]
  [-0.78898902]
  [-1.26160595]
  [ 0.56284679]
  [-0.24332625]
  [ 0.9137407 ]
  [ 0.31735092]
  [ 0.12730328]
  [ 2.15038297]
  [ 0.60628866]
  [-0.02677165]
  [-0.98416078]
  [ 1.19070527]
  [ 0.95283061]


In [33]:
# 定义卷积层
filters = 1 # 卷积核数量为 1
kernel_size = 5 # 卷积核大小为 5
convolution_1d_layer = keras.layers.convolutional.Conv1D(filters, kernel_size, strides=1, padding='valid', input_shape=(25, 1), activation="relu", name="convolution_1d_layer")

# 定义最大化池化层
max_pooling_layer = keras.layers.MaxPool1D(pool_size=5, strides=1, padding="valid", name="max_pooling_layer")

# 平铺层，调整维度适应全链接层
reshape_layer = keras.layers.core.Flatten(name="reshape_layer")

# 定义全链接层
full_connect_layer = keras.layers.Dense(5, kernel_initializer=keras.initializers.RandomNormal(mean=0.0, stddev=0.1, seed=seed), bias_initializer="random_normal", use_bias=True, name="full_connect_layer")

# 编译模型
model = keras.Sequential()
model.add(convolution_1d_layer)
model.add(max_pooling_layer)
model.add(reshape_layer)
model.add(full_connect_layer)

# 打印 full_connect_layer 层的输出
output = keras.Model(inputs=model.input, outputs=model.get_layer('full_connect_layer').output).predict(data_1d)
print(output)

# 打印网络结构
print(model.summary())

[[ 0.8476372  -0.332788   -0.17554513  1.2284881   0.59770095]]
Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
convolution_1d_layer (Conv1D (None, 21, 1)             6         
_________________________________________________________________
max_pooling_layer (MaxPoolin (None, 17, 1)             0         
_________________________________________________________________
reshape_layer (Flatten)      (None, 17)                0         
_________________________________________________________________
full_connect_layer (Dense)   (None, 5)                 90        
Total params: 96
Trainable params: 96
Non-trainable params: 0
_________________________________________________________________
None


In [36]:
import numpy as np

a = np.array([[1,2],[3,4]])
sum0 = np.sum(a, axis=0)
sum1 = np.sum(a, axis=1)

print(sum0)
print(sum1)


[4 6]
[3 7]
