In [117]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series
from sklearn.model_selection import train_test_split
def seq_to_mat(seq):
    seq_len = len(seq)
    seq = seq.replace('A', '0')
    seq = seq.replace('a', '0')
    seq = seq.replace('C', '1')
    seq = seq.replace('c', '1')
    seq = seq.replace('G', '2')
    seq = seq.replace('g', '2')
    seq = seq.replace('T', '3')
    seq = seq.replace('t', '3')
    seq = seq.replace('U', '3')
    seq = seq.replace('u', '3')
    seq = seq.replace('N', '4')
    seq = seq.replace('n', '4')
    seq_code = np.zeros((4, seq_len), dtype='float16')
    for i in range(seq_len):
        if int(seq[i]) != 4:
            seq_code[int(seq[i]), i] = 1
        else:
            seq_code[0:4, i] = np.tile(0.25, 4)
    return np.transpose(seq_code)

In [118]:
#####################
##Load the data######
#####################

df = pd.read_csv('/Users/hopezhu/PycharmProjects/DL/seqdata_eif3a_full/eif3a_Full_20.csv')
print(df)

      Unnamed: 0   num                                  train_All  \
0              1     1  GTATGTGGGGCCGTGTGCAGACCCGCGTGTGGCGCAGGCAA   
1              2     2  GGTGAGGGGGATGTGGCAGGACTATAAGGTAATGGTGGGGA   
2              3     3  TTTTCCTTCCCCTAGCTTTGACTTTTCTTATGGTCTGTGAG   
3              4     4  GTGAACTAACTTTACTTAAAACCGGGTTAAATGTTTGTTAC   
4              5     5  CCGCACTGGCCTGGGAGCGGACCCCGGACTACACACGGCTT   
...          ...   ...                                        ...   
1205        1206  1206  TTTGGATGAGGTCTGGTAAGACTGAGACTTTTTAAATTTTG   
1206        1207  1207  AATCGGAAATGACCAAAGGGACATTACCATCAACCCCACAG   
1207        1208  1208  TCTGAGCAGTGTGGGGGAAGACCAGGGCTCTGGGCACGGCA   
1208        1209  1209  ATCAGTAAAGGAAGTGAAAGACAGGATTGCATTTAATAGAT   
1209        1210  1210  TGTAAGTTTCTCTTTTAAAAACTAAGCGGTCGAGCATGGTG   

                                    testing_All  
0     ACACCAAAATGCTGCAGTGAACATTCTTGCATGTACATGTT  
1     TGAGAGGCTGTTTGACATAGACCAAAGAAGAAACTGGAAGA  
2     CATCCCAGGAGAGAA

In [119]:
train_All_1 = df.iloc[:, 2]
test_all_1 = df.iloc[:, 3]
print(train_All_1.shape[0])
# print(test_all_1)

1210


In [120]:
len(test_all_1[0])

41

In [121]:
X_train = np.array(train_All_1)
X_train
print(X_train)
lt = []
for seq in X_train:
    x = seq_to_mat(seq)
    lt.append(x)

x_train = np.array(lt)
# print(x_train)
# print(x_train.shape)

['GTATGTGGGGCCGTGTGCAGACCCGCGTGTGGCGCAGGCAA'
 'GGTGAGGGGGATGTGGCAGGACTATAAGGTAATGGTGGGGA'
 'TTTTCCTTCCCCTAGCTTTGACTTTTCTTATGGTCTGTGAG' ...
 'TCTGAGCAGTGTGGGGGAAGACCAGGGCTCTGGGCACGGCA'
 'ATCAGTAAAGGAAGTGAAAGACAGGATTGCATTTAATAGAT'
 'TGTAAGTTTCTCTTTTAAAAACTAAGCGGTCGAGCATGGTG']


In [122]:
test = DataFrame(test_all_1)
test = test.dropna()

print(test.shape[0])

302


In [123]:
lst_test = []
x_val=test_all_1[0:test.shape[0],]
# test_all_1[0:x_val.shape]
# x_val
#
print(x_val)

0      ACACCAAAATGCTGCAGTGAACATTCTTGCATGTACATGTT
1      TGAGAGGCTGTTTGACATAGACCAAAGAAGAAACTGGAAGA
2      CATCCCAGGAGAGAATGAGGACCCTGTCGGAATCATAAGGG
3      AAATTAGTATAAGTCATTAAACTAAAAAGATTTCTAAATGG
4      AGTACTACAGAATGGCAGGGACAGTGAAAATGAGCATTCTT
                         ...                    
297    GACATGAGTAATCATTTTGAACAAAAGTTTATTAGAGTTTT
298    AGGCAAATGGGTGGGGATAGACAGGAGATGGGCAGAGGTAG
299    TTTATTATTTATTTATTGAGACAGGGTCTCACTCTGTCACC
300    TAATTATTTCTAGATGCAAAACTAGTGAGTTTACCATGTTC
301    TCTGCACTCTGGCCTGGGTGACAGAGCGACACTCCATCTCA
Name: testing_All, Length: 302, dtype: object


In [124]:
for seqs in x_val:
    x = seq_to_mat(seqs)
    lst_test.append(x)

In [125]:
x_val = np.array(lst_test)
print(x_val)

[[[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]]

 [[0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]
  [0. 0. 1. 0.]]

 ...

 [[0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  ...
  [1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 0. 1.]
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]]

 [[0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 0. 1.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]]


In [126]:
y_train = np.array([1, 0])
y_train = y_train.repeat(train_All_1.shape[0]/2)
print(y_train)
y_train = np.mat(y_train).transpose()
print(len(y_train))

[1 1 1 ... 0 0 0]
1210


In [127]:
y_val = np.array([1, 0])
y_val = y_val.repeat(test.shape[0]/2)
# print(y_val)
y_val = np.mat(y_val).transpose()
# print(len(y_val))

x_val, x_test, y_val, y_test = train_test_split(x_val, y_val, test_size=0.5)
print(x_val)
print(x_train.shape)
print(x_test.shape)
print(y_val.shape)
print(y_train.shape)
print(y_test.shape)




[[[0. 1. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]]

 [[1. 0. 0. 0.]
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [0. 0. 0. 1.]
  [0. 0. 1. 0.]]

 ...

 [[1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  ...
  [0. 0. 1. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]

 [[0. 0. 0. 1.]
  [1. 0. 0. 0.]
  [0. 0. 0. 1.]
  ...
  [0. 0. 1. 0.]
  [0. 1. 0. 0.]
  [1. 0. 0. 0.]]

 [[1. 0. 0. 0.]
  [0. 1. 0. 0.]
  [0. 1. 0. 0.]
  ...
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]
  [1. 0. 0. 0.]]]
(1210, 41, 4)
(151, 41, 4)
(151, 1)
(1210, 1)
(151, 1)


In [130]:
len("ACACCAAAATGCTGCAGTGAACATTCTTGCATGTACATGTT")

41

In [131]:
len('CCAAACCTTTGCTGCTACAAACACCAAAATGCTGCAGTGAACATTCTTGCATGTACATGTTTACATACATATGCAGTATAA')

81

In [132]:
len('GGCCGCGTGGGCGAGGCGGAGGAGAGCCGTGCGCAGCGGCGTATGTGGGGCCGTGTGCAGACCCGCGTGTGGCGCAGGCAAGGACCCTCAAAATAAACAGCCTCTACCTTGCGAGCCGTCT')

121

In [133]:
len('GTATGTGGGGCCGTGTGCAGACCCGCGTGTGGCGCAGGCAA')

41

In [134]:
len('CCGAACCCCGCGCGCTGATTGGCCGCGTGGGCGAGGCGGAGGAGAGCCGTGCGCAGCGGCGTATGTGGGGCCGTGTGCAGACCCGCGTGTGGCGCAGGCAAGGACCCTCAAAATAAACAGCCTCTACCTTGCGAGCCGTCTTCCCCAGGCCTGCGTCCGAG')

161